### ISSUE TITLE
Hash algorithm other than sha256 for `customs-buffer-hash`?

### ISSUE THREAD

**Issue by KB5201314** [CCC-Attestation/interoperable-ra-tls#4]
According to the following description in the documentation:
https://github.com/CCC-Attestation/interoperable-ra-tls/blob/a2c2323377007aa27b5ceb453a741a860e0245a0/docs/Interoperable-RA-TLS-cert-edvidence-formats.md?plain=1#L21-L22
The `pubkey-hash-value` is a `hash-entry`, which I think the purpose is to leave space for choosing a stronger hash algorithm than sha256 in the future.

Also we have the following description for `custims-buffer-hash`:
https://github.com/CCC-Attestation/interoperable-ra-tls/blob/a2c2323377007aa27b5ceb453a741a860e0245a0/docs/Interoperable%20Attested%20TLS%5CInteroperable-RA-TLS-SGX-TDX-evidence-formats.md?plain=1#L21-L26

Considering that `custims-buffer-hash` is located in the chain of trust of `pubkey-hash-value`, why not change `customs-buffer-hash` to a `hash-entry` like structure as well, so that we can choose a hash algorithm other than sha256 for `custims-buffer-hash`?

**Comment by dimakuv** [comment]
> Considering that `custims-buffer-hash` is located in the chain of trust of `pubkey-hash-value`, why not change `customs-buffer-hash` to a `hash-entry` like structure as well, so that we can choose a hash algorithm other than sha256 for `custims-buffer-hash`?

@KB5201314 I don't think this is allowed by current SGX/TDX hardware.

The ECDSA quote (aka SGX quote, aka TDX quote) has a field `REPORTDATA` (aka "user data field"). This field is hardware-defined and is **64 bytes in size**.

Thus, whatever format we choose for `customs-buffer-hash`, it must definitely fit into 64 bytes. Having a `hash-entry` like structure means something like this:
```c
struct __attribute__((packed)) hash-entry {
    uint8_t hash-alg-id;  /* 8 bytes in size */
    char hash-value[56];  /* can be at most 56 bytes */
}
```

So even using a compact C representation above, we are restricted to only those hash functions that fit into 56 bytes. For example, SHA-512 will **not** fit here.

Moreover, if we use a standard CBOR representation for the struct above, some bytes will be eaten by the CBOR metadata itself. So we'll end up having even less bytes available for the hash...

All in all, I think SHA-256 is a valid choice, and we can't do much better.

**Comment by KB5201314** [comment]
@dimakuv Thank you for pointing this out. I agree with you.
