### ISSUE TITLE
The interoperability testing between Gramine and rats-tls

### ISSUE THREAD

**Issue by jiazhang0** [CCC-Attestation/interoperable-ra-tls#8]
Current testing model is: Gramine as client and attester vs rats-tls as server and verifier (mtls)

The rats-tls contains sample server program (see https://github.com/inclavare-containers/rats-tls/tree/master/samples for the source codes). 

At present, the sample server program doesn't run in a TEE, just in host, providing a self-signed TLS certificate.

---

For the local testing for the case "rats-tls as client and attester vs rats-tls as server and verifier (mtls)", simply run:

```
git clone https://github.com/inclavare-containers/rats-tls
cd rats-tls
cmake -DRATS_TLS_BUILD_MODE="host" -DBUILD_SAMPLES=on -H. -Bbuild
make -C build install
cd /usr/share/rats-tls/samples
RATS_TLS_GLOBAL_LOG_LEVEL=debug ./rats-tls-server --log-level debug --attester nullattester --verifier sgx_ecdsa --mutual
```

The client side command is:
```shell
./rats-tls-client --log-level debug --attester sgx_ecdsa --verifier nullverifier --mutual
```

By default, the listening port is 1234. -p option can be used to overwrite the default port.

**Comment by KB5201314** [comment]
> ```
> git clone https://github.com/KB5201314/rats-tls -b dice-extensions
> ```

@jiazhang0 This branch has been merged, so we can directly use the code in [inclavare-containers/rats-tls](https://github.com/inclavare-containers/rats-tls) repo.

```sh
git clone https://github.com/inclavare-containers/rats-tls
```
